### ISSUE TITLE
Ensure handling of missing opening/closing tags for all HTML5 elements

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#101]
Right now the lexer contains a set of rules that can be used to close certain elements that are left open, based on a newly found opening tag. These rules are mostly based on those found at http://www.w3.org/TR/html5/syntax.html#optional-tags but this list doesn't contain the rules for all elements (how convenient). As such it's best to review _every single HTML element_ and add any missing rules.

**Comment by YorickPeterse** [comment]
Another case as per #99, consider the following HTML:

```html
<table>
    <tbody>
        <tr>
            <td>Ms Danus
</table>

<form id=f action="/auction.cgi">
    <input type=button name=add value="Submit">
</form>
```

Because Oga doesn't really care about the name of closing tags it effectively lexes it as following:

```html
<table>
    <tbody>
        <tr>
            <td>Ms Danus
</td>

<form id=f action="/auction.cgi">
    <input type=button name=add value="Submit">
</form>
```

When parsing this and serializing it back to HTML we get the following output:

```html
<table>
    <tbody>
        <tr>
            <td>Ms Danus
</td>

<form id="f" action="/auction.cgi">
    <input type="button" name="add" value="Submit" />
</form>
</tr></tbody></table>
```

The only sustainable way of resolving this problem is to add a hierarchy of all HTML5 elements and the elements that can be nested in them. Any element that is not in such a list results in left-open tags being closed automatically. 

In the example above we know that a `<form>` element can not reside in a `<td>`, `<tr>`, `<thead>` and `<table>` element, thus we'd first close all those tags before processing the opening `<form>` tag.

An alternative would be to add a hook when processing closing tags to automatically close any left-open tags based on a heuristic similar to those used for open tags. This however would require a similar (if not the same) hierarchy of elements and their allowed child elements.

**Comment by YorickPeterse** [comment]
When using the hierarchy mentioned above the process of closing tags is basically as following:

1. Take the name of the element we're currently in, get all the elements that are allowed to reside within it
2. Check if the name of the opening element we're about to process is in this list
3. If this is not the case close the element that was left open, jump back to step 1
4. If this _is_ the case just continue business as usual

**Comment by abotalov** [comment]
> In the example above we know that a `<form>` element can not reside in a `<td>`, `<tr>`, `<thead>` and `<table>` element

That's not true.

The `form` element can be used [where flow content is expected](http://www.w3.org/TR/html51/semantics.html#the-form-element). The `td` element's [content model is flow content](http://www.w3.org/TR/html51/semantics.html#the-td-element) so `td` element may contain `form` element.

In an example above `form` element doesn't belong to `td` because `table` element is closed and the series of rules:
> A tbody element's end tag may be omitted if ... there is no more content in the parent element.
A tr element's end tag may be omitted if ... there is no more content in the parent element.
A td element's end tag may be omitted if ... there is no more content in the parent element.

**Comment by YorickPeterse** [comment]
@abotalov In the above example Oga doesn't know it's the `<table>` element that's being closed. In fact, it will treat this as closing the `<td>` element. A `<tr>`, `<tbody>` and `<table>` still can't contain a `<form>` as far as I'm aware of.

**Comment by YorickPeterse** [comment]
The procedure I'll be going with (unless I bump into any big problems) is as following:

1. Build a Hash of all elements and their allowed child elements, elements not in this Hash (as the keys) are treated as elements that can't have any child elements (e.g. `<title>`).
2. When we bump into a new open tag while we're still in an unclosed tag, check if said new tag is allowed inside the unclosed tag. If this is not the case the unclosed tag is closed first.

The exception here is the `<body>` element. While officially only a subset of elements is allowed in a `<body>` (e.g. `<body><tr>foo</tr></body>` is invalid I believe) Oga will instead allow everything _except_ another `<body>` or `<head>` tag. This ensures that HTML such as this:

```html
<body>
    <tr>foo
```

is parsed as this:

```html
<body>
    <tr>foo</tr>
</body>
```

instead of this:

```html
<body></body>
<tr>foo</tr>
```

For the form example this would result in the following steps:

1. `current_element` returns `tr`, the new element is `form`
2. `form` is not allowed in `tr`, close `tr` first
3. `form` is not allowed in `tbody`, close `tbody` first
4. `form` is not allowed in `table`, close `table` first
5. `form` _is_ allowed in `<body>`, continue business as usual

Steps 2-5 would basically be a `while` loop.

**Comment by abotalov** [comment]
> When we bump into a new open tag while we're still in an unclosed tag, check if said new tag is allowed inside the unclosed tag. If this is not the case the unclosed tag is closed first.

I don't think it's correct. New elements may appear in HTML spec and it's not correct to say that such new elements can't contain any content.

Also it's possible to use custom elements - http://stackoverflow.com/questions/9845011/are-custom-elements-valid-html5

**Comment by abotalov** [comment]
I think the list of optional tags listed [here](http://www.w3.org/TR/html51/syntax.html#optional-tags) is full. No other elements may have end tags that can be omitted.

**Comment by YorickPeterse** [comment]
The bulk of this should be taken care of in commits https://github.com/YorickPeterse/oga/compare/3e337faa1d9708835aaf4e81d16910e01ed894d5...688a1fff0efb9e2405e0aab5b3a7164e78ec287e. I still have to add new specs for a bunch of HTML elements and verify if all is well know, but so far it's looking quite promising.

**Comment by YorickPeterse** [comment]
@abotalov Could you give the latest master version a try with some HTML you might have around? As far as I can tell it _should_ be taken care of now, but I want to be 100% sure it's good to go this time :)

**Comment by YorickPeterse** [comment]
Closing this as it should be fixed, feel free to re-open if needed.

**Comment by abotalov** [comment]
https://github.com/w3c/web-platform-tests/blob/master/html/semantics/interactive-elements/the-details-element/details.html
In this example `p` tag should be closed prior to `details` tag as it's immediately followed by it:
> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul, element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element.

**Comment by abotalov** [comment]
One more example:
```html
 <object>
  <ul>
   <li>Li
  </ul>
  Inside object
 </object>
 Outside object
```
is currently equivalent to:
```html
 <object>
  <ul>
   <li>Li
  </li>
  Inside object
 </ul>
 Outside object
</object>
```

**Comment by YorickPeterse** [comment]
> I think that's because elements that appeared in HTML 5.1 spec haven't been added.

Ah good point, those of the `p` element were still based on 5.0. This has been taken care of in 3c6263d8de30b91aac7c3b16b65f00407b88fc13

Regarding the last example, I'm moving that to a separate issue.
