### ISSUE TITLE
mechanize + nokogiri --> mechanize + oga

### ISSUE THREAD

**Issue by muescha** [YorickPeterse/oga#106]
i use mechanize which requires nokogiri (which is a PITA to install)

is it possible to have a mechanize + oga?

**Comment by davidcelis** [comment]
Someone would either need to fork mechanize to create a version that uses Oga, or submit a pull request to Mechanize that replaces the dependency.

**Comment by YorickPeterse** [comment]
@muescha No idea, I don't use mechanize myself and I'm not sure how heavily it depends on Nokogiri specifics. Personally I usually use a mix of HTTPClient (https://github.com/nahi/httpclient) and Oga, though this requires a bit more manual tinkering.

Having said that, feature requests such as these are probably best submitted to the mechanize repository itself, I can't do much about their choice of libraries.

**Comment by muescha** [comment]
i think the eazy form handling from mechanize i need to rebuild with httpclient/oga or are there some helper gems?

**Comment by YorickPeterse** [comment]
@muescha I do not understand your question. Please keep in mind that I can't help you with any Mechanize related questions as I don't use Mechanize myself.
