### ISSUE TITLE
Support for strict parsing of XML

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#107]
After this being requested 3 times now I think it's time I start looking into this. Most of this can probably be achieved by putting the automatic closing code in a condition such as `unless strict? .... end`. While technically this could also be used for HTML I'm not sure how useful that would be. Most websites are either using HTML5 or some broken form of XHTML/HTML4 which probably won't work with strict mode.

Usage wise there are two ways this can be exposed:

* Using an option such as `Oga.parse_xml('...', :strict => true)`
* Using a bang method such as `Oga.parse_xml!('...')`

I'm not sure yet which one I prefer.

**Comment by YorickPeterse** [comment]
Looking at things the only difference in strict mode would be the removal of automatically inserting missing closing tags. Everything else is handled in the Ragel code and I don't want to litter it with more conditionals (as this is a pain to maintain).

@trevorrowe: you mentioned the AWS SDK needs some sort of error handling due to services using chunked transfers without setting the chunk sizes. How exactly would you use error handling in this case?

**Comment by trevorrowe** [comment]
Sorry for the slow reply.

It is possible to receive truncated responses from a few services. When the service does not send a content length with the response, it is not possible to do a simple bytes received check. In these cases, I expect the XML or JSON parser to raise an error when the document is not well-formed. AWS services should only return strictly valid XML documents.

If the parser is inserting missing closing tags, that is sufficient for me to assert that something is wrong with the response. Currently the SDK has the ability to retry these failed responses.

**Comment by YorickPeterse** [comment]
@trevorrowe I added basic strict parsing support in 2c18a51ba905d46469170af7f071b068abe965eb, could you build from Git [1] and give that a try?

[1]: `git clone` the repository, run `bundle install` followed by `rake`. You can then simply run `rake install` to install the Gem.

**Comment by trevorrowe** [comment]
@YorickPeterse Works great! I pushed a [branch of `aws-sdk`](https://github.com/aws/aws-sdk-ruby/commit/2cdb5244e836b1fdf318872609d3d160d1dd388b) that uses Oga which passes all of the SDK XML parser and protocol tests.

**Comment by YorickPeterse** [comment]
Fantastic! I'll push a new Gem release later today.

**Comment by YorickPeterse** [comment]
@trevorrowe This has been released in Oga 1.0.3 (http://code.yorickpeterse.com/oga/latest/file.CHANGELOG.html).
