### ISSUE TITLE
Unexpected T_STRING_DQUOTE, expected element closing tag instead

### ISSUE THREAD

**Issue by adwell** [YorickPeterse/oga#109]
Hi guys! How far along is oga at recovering from bad html? This sort of problem is pretty common out in the wild:

```ruby
Oga.parse_html('<div width=97%"></div>')
```

LL::ParserError: Unexpected T_STRING_DQUOTE, expected element closing tag instead on line 1

**Comment by abotalov** [comment]
http://www.w3.org/TR/html51/syntax.html#attribute-value-(unquoted)-state
Here it's said that such syntax leads to a parse error. But also it says that a quote should be considered part of the attribute value - "Treat it as per the "anything else" entry below."

Google Chrome parses it as (seems to be according to the spec):
```html
<div width="97%&quot;"></div>
```
