### ISSUE TITLE
to_xml doesn't handle quotes inside attribute values well

### ISSUE THREAD

**Issue by abotalov** [YorickPeterse/oga#113]
Same bug as https://github.com/jhy/jsoup/issues/528

```ruby
puts Oga.parse_html('<img a="&quot;">').to_xml
<img a=""" />
```

**Comment by YorickPeterse** [comment]
There are two ways of solving this that I can think of at the moment:

1. Convert entities back to their encoded form when calling `to_xml`.
2. Only escape a double quote using a `\` (I believe this is valid in XML/HTML).

Personally I'm not a huge fan of option 1.

**Comment by YorickPeterse** [comment]
Thinking of it using a backslash probably won't work, at least Nokogiri doesn't really seem to like it. Nokogiri seems to URL encode the values, e.g. `"` ends up as `%22`. Not sure if this the official way of doing it though.

**Comment by abotalov** [comment]
I've found the following section in the spec - http://www.w3.org/TR/html51/syntax.html#serialising-html-fragments

The following part seems to be interesting:
```
If the algorithm was invoked in the attribute mode, replace any occurrences of the """ character by the string "&quot;".
If the algorithm was not invoked in the attribute mode, replace any occurrences of the "<" character by the string "&lt;", and any occurrences of the ">" character by the string "&gt;".
```

Google Chrome's behavior seems to be consistent with this:
```html
<div a="&lt;&gt;&quot;">&lt;&gt;&quot;</div>
```
leads to the following HTML:
```html
<div a="<>&quot;">&lt;&gt;"</div>
```

**Comment by YorickPeterse** [comment]
That might also be an option and would remove the need for using the `URI` library. It would however require a way to whitelist the entities to encode as I don't think there's a need for encoding everything when re-generating attribute values.
