### ISSUE TITLE
Escaping characters in css selectors doesn't work

### ISSUE THREAD

**Issue by abotalov** [YorickPeterse/oga#124]
Same bug as https://github.com/sparklemotion/nokogiri/pull/1303

Characters can be escaped in CSS selectors using backslashes - http://www.w3.org/TR/css3-selectors/#selector-syntax

From http://www.w3.org/TR/CSS21/syndata.html#characters:
> Any character (except a hexadecimal digit, linefeed, carriage return, or form feed) can be escaped with a backslash to remove its special meaning. For example, "\"" is a string consisting of one double quote.

> Third, backslash escapes allow authors to refer to characters they cannot easily put in a document. In this case, the backslash is followed by at most six hexadecimal digits (0..9A..F)

**Comment by YorickPeterse** [comment]
I'm not sure if Oga will support escaping arbitrary characters (as supporting this is quite painful from the top of my head, but I'll see) but at least it will support escaping the following:

* dots
* hashes
* whitespace

This would let you write queries such as `#foo\.bar` to match `<div id="foo.bar" />` which will probably cover 95% of all cases.
