### ISSUE TITLE
CSS :not pseudo class isn't supported

### ISSUE THREAD

**Issue by abotalov** [YorickPeterse/oga#125]
It's specified in http://www.w3.org/TR/css3-selectors/#negation

**Comment by YorickPeterse** [comment]
This can be directly mapped to the XPath `not()` function so adding this is fairly easy. If somebody wants to add it feel free to do so, otherwise I'll add it myself once I'm done with the XPath compiler.

**Comment by YorickPeterse** [comment]
Do note that document states such as `DISABLED` can't be supported as Oga is not a browser. The same goes for pseudos such as `:link` and `:visited`.
