### ISSUE TITLE
HTML element names are matched case-sensitively when using XPATH/CSS selectors

### ISSUE THREAD

**Issue by abotalov** [YorickPeterse/oga#127]
Currently Oga matches element/attribute names/values in xpath/css selectors in a case sensitive way.
```ruby
doc = Oga.parse_html('<!DOCTYPE html><DIV></DIV>')
doc.css('DIV') # => NodeSet(Element(name: "DIV"))
doc.css('div') # => NodeSet()
doc.xpath('//div') # => NodeSet()
```

However, in reality case matching of element names is sensitive in XML but is case insensitive in HTML.

See http://www.w3.org/TR/html51/semantics.html#case-sensitivity and http://dev.w3.org/csswg/selectors/#case-sensitive in regard to CSS selectors.

I didn't find a relevant section in specifications about XPath and HTML. Browsers match element names case-insensitively.

Case matching of attribute names and values seems to be a bit more quirky though. Not sure if any change in Oga is needed. Here are some results from Google Chrome when trying to find element
```html
<input type="text" class="cls">
```
```
$$('.cls') => found
$$('.CLS') => not found
$$('INPUT[TYPE=TEXT]') => found
$$('INPUT[CLASS=cls]') => found
$$('INPUT[CLASS=CLS]') => not found
$x("//INPUT[@type='text']") => found
$x("//INPUT[@TYPE='text']") => not found
```

The following links might be worth checking:
http://sourceforge.net/p/htmlunit/bugs/764/
https://www.w3.org/Bugs/Public/show_bug.cgi?id=24005

**Comment by gurgeous** [comment]
Can you just make them all case insensitive? This seems like the right choice for handling dirty input.

**Comment by YorickPeterse** [comment]
Attribute values will be kept as-is since `foo="bar"` and `foo="BAR"` are two very different values. Element names will most likely always be case insensitive as I believe keeping it case sensitive for XML only is confusing.
