### ISSUE TITLE
Preserving HTML character entity references

### ISSUE THREAD

**Issue by omninonsense** [YorickPeterse/oga#133]
Currently, Oga decodes HTML/XML character entity references (let's call 'em just "entities" from onward) one-way:

~~~ruby
Oga::parse_html('&#x2764;').to_xml
# => "❤"
~~~

There is no way to encode unicode back into entities, or at least I [think so][why-i-think-so].

I recommend the following: add methods `Oga::XML::Node#encode` and `Oga::XML::Document#encode` which recursively descend into its children, to encode all `Oga::XML::Text` nodes they encounter. The method would encode everything that's:

- outside the ASCII range
- has special meaning to HTML/XML

### Things to consider:

- Should it additionally attempt a lookup against `Oga::HTML::Entities::DECODE_MAPPING` (using `Hash#key`), and encode those as `&str;`, or just encode everything using the numeric format?
- Which numeric format to use (required at least for non-mapped entities) `&#dddd;` or `&#xhhhh;`?

---

I'm willing to add this after everyone agrees on the details and no one has any objections to the feature, or if someone isn't working on it already.

[why-i-think-so]: https://github.com/YorickPeterse/oga/blob/6786dde3f02a738fac0f4ef1a0936873481f1c60/lib/oga/xml/entities.rb#L86-L122

**Comment by omninonsense** [comment]
Oh, and I forgot to mention, I vote for `&#xhhhh;`, because it's easier to recognise (visually) those as unicode codepoints over the decimal counterparts.

Also because they might turn out a few bytes shorter than the decimal ones (might be `false`)?

**Comment by YorickPeterse** [comment]
What's the use case for this? Characters that are not legal XML/HTML (e.g. a literal `<` in an element's body) are already encoded upon output, any other characters are legal XML/HTML characters as far as I'm aware.

Unless there's a good reason for this I'm quite reluctant to add this because:

1. Recursively encoding all non ASCII character sequences is more painful than having to listen to drunken roosters trying to sing Justin Bieber songs. It will also have a pretty serious impact on serialization performance.
2. This will produce output different from previous 1.x versions. This _might_ break applications, and I'd rather not do that at this time (or bumping the version to 2.x).

**Comment by omninonsense** [comment]
The use case could be the user is limited to outputting an ASCII-only stream&mdash;for whatever reason.

I don't find the first part of **1** to be that problematic, however I *do* agree that it might case performance issues; **2** didn't cross my mind, actually.

About second part of **1** and **2**, the solution could be something along the lines of adding Node#encode, which accepts a block/Proc?

During serialization, the node would be encoded using its own encoder.

Set the default encoder for each node to the current encoder (encoding only HTML significant symbols). Setting the encoder on a Node makes all child nodes inherit that encoder.


#### Usage example

Input:
~~~html
<span>おが <span class="entities">❤</span> &#x30a8;&#x30f3;&#x30b3;&#x30fc;&#x30c7;&#x30a3;&#x30f3;&#x30b0;</span>
~~~

Ruby code:
~~~ruby
document = Oga::parse_html(input)

to_hex_entity = Proc.new do |cp|
  if (ch = cp.chr Encoding::UTF_8).ascii_only? then ch else "&#x#{cp.to_s 16};" end
end

document.css('.entities').each do |element|
  element.encode(&to_hex_entity)
end

document.to_xml
~~~

Output:
~~~html
<span>おが <span class="entities">&#x2764;</span> エンコーディング</span>
~~~

---

I realise that a per-node encoding might be overkill, and that the user can encode the serialized string before sending it for further processing. More control isn't required, but nice and useful in certain scenarios I believe users should be forced into a single way of serializing the content (IHMO).

**Comment by YorickPeterse** [comment]
I'm going to close this as "wontfix". The performance impact and complexity needed to support this far outweighs the usefulness of this feature. I may reconsider this in the future if there is enough demand for this and it can be implemented in a way that doesn't slow down serializing documents to XML.
