### ISSUE TITLE
HTML 4 doesn't have &apos;

### ISSUE THREAD

**Issue by xzo** [YorickPeterse/oga#137]
The named character reference `&apos;` (the apostrophe, U+0027) was introduced in XML 1.0 but does not appear in HTML. Authors should therefore use `&#39;` instead of `&apos;` to work as expected in HTML 4

http://www.w3.org/TR/xhtml1/#C_16

**Comment by YorickPeterse** [comment]
Oga's HTML support follows the HTML5 specification which _does_ have `&apos;`. I'm not going to add support for different HTML versions as doing so complicates the code too much for very little gain.
