### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by EHadoux** [YorickPeterse/oga#145]
Hello,

I have a performance question. Let's say we have an HTML doc like this:
```html
<div id=1>
  <div id=2>
    <img/>
    <img/>
  </div>
  <div id=3>
    <span/>
  </div>
</div>
```

I want to get all the images and the span.
What is the best to do?
1:
```ruby
doc = parse_html()
one = doc.at_css("#1")
imgs = one.css("#2 img")
span = one.css("#3 span")
```
or 2:
```ruby
doc = parse_html()
imgs = doc.css("#2 img")
span = doc.css("#3 span")
```

of course, I have way more descendants and siblings.
I guess that 1) is more time efficient but uses more memory (the chunk in one) and 2) is the opposite.
But I think you know better.

Thanks!

**Comment by YorickPeterse** [comment]
Generally the fastest way to get a set of elements is to use the XPath axis `descendant` or `descendant-or-self` (if you also want to match the current context node). For example:

```ruby
require 'oga'

doc = Oga.parse_html <<-EOF
<div id=1>
  <div id=2>
    <img/>
    <img/>
  </div>
  <div id=3>
    <span/>
  </div>
</div>
EOF

doc.xpath('descendant-or-self::img | descendant-or-self::span')
```

If you want to scope them to a `div` you'd simply change the xpath query to:

    doc.xpath('div/descendant-or-self::img | div/descendant-or-self::span')

If you _only_ want to grab either images of spans you can also just use CSS, e.g.:

    doc.css('div img')

This query is basically the same as XPath `descendant::div/descendant::img`.

Having said that, CSS selectors don't allow you to concatenate multiple node sets together in a single query (at least that I can remember) so you'd have to do this manually.

**Comment by EHadoux** [comment]
Ok, I see, thanks.
However, I want to have them in different variables so I guess the ```'div/descendant-or-self::img | div/descendant-or-self::span'``` won't help me. My question was in fact: is it really better to get out the div scope and fetch what I want from that scope (if I was several stuffs to get) than to always fetch from doc and thus going all the way down in the html source each time?
I mean, in my example 1, I take out the div 1 from the whole doc and make my query on it instead of on the whole doc.
In the other hand, I guess for my example 2 that the parser goes from the very beginning each time I call .css right?

**Comment by YorickPeterse** [comment]
If you know the container before hand and you expect to extract multiple elements from it using different queries then yes, it's faster to first grab the container. Example:

```ruby
doc = Oga.parse_html('...')
container = doc.css('some_div')

container.css('foo')
container.css('bar')
container.css('...')
```

**Comment by EHadoux** [comment]
Perfect, thanks!
