### ISSUE TITLE
stop the escaping when using #inner_text

### ISSUE THREAD

**Issue by cj** [YorickPeterse/oga#150]
Evening,

Is there a way to stop it from escaping html when setting the inner_text?

**Comment by cj** [comment]
The only way I can think of would be to `Oga.parse_html(your_inner_text)` and then append it to the node you were going to set the inner_text of.

**Comment by YorickPeterse** [comment]
I'm not sure what the question is here, merely setting an element's inner text performs no escaping. Could you provide a code sample of what you're talking about?

**Comment by cj** [comment]
```ruby
html = Oga.parse_html(some_html)
html.css('#some_div').first.inner_text = '<h1>foo</h1>'
```

#some div is now `&lt;h1&gt;test&lt;/h1&gt;` instead of `<h1>test</h1>`

**Comment by YorickPeterse** [comment]
@cj The method `#inner_text=` is meant to set text, _not_ html. There's no way to insert HTML nodes using Strings like the example you've provided.
