### ISSUE TITLE
Expand enumerable section of README

### ISSUE THREAD

**Issue by TearADactile** [YorickPeterse/oga#151]
It is not clear to me how i should be using an enumerable to operate on a big xml let alone extract data with an xpath/css.  

An expansion of this section in the readme would be greatly appreciated.

Thank you!

**Comment by YorickPeterse** [comment]
@TearADactile Using an Enumerator doesn't apply to extracting data with XPath/CSS, it's only used during the parsing phase. There's one example using HTTPClient in the README, are there any other particular examples you'd like to see?

**Comment by YorickPeterse** [comment]
Closing this since I'm not sure what needs to done to improve the docs in question and no suggestions have been made thus far.
