### ISSUE TITLE
Oga under-performs against Nokogiri

### ISSUE THREAD

**Issue by Zapotek** [YorickPeterse/oga#152]
Based on [this feature claim](https://github.com/YorickPeterse/oga/blame/master/README.md#L161) I thought I'd report this:

```ruby
require 'benchmark/ips'
require 'oga'
require 'nokogiri'

HTML = <<EOHTML
    <root xmlns:x="foo"><x:div></x:div></root>
EOHTML

Benchmark.ips do |x|
    x.report( 'Nokogiri::HTML' ) do |times|
        times.times do |i|
            Nokogiri::HTML( HTML )
        end
    end

    x.report( 'Oga' ) do |times|
        times.times do |i|
            Oga.parse_html( HTML )
        end
    end
end
```

```
Warming up --------------------------------------
      Nokogiri::HTML     2.515k i/100ms
                 Oga     1.616k i/100ms
Calculating -------------------------------------
      Nokogiri::HTML     27.095k (± 1.5%) i/s -    135.810k
                 Oga     16.830k (± 1.7%) i/s -     85.648k
```

I was hoping for a faster Nokogiri replacement but if I'm reading the above correctly Oga under-performs.
It's even worse for larger documents.

Is there a benefit down the line, maybe while iterating or manipulating the document?

**Comment by YorickPeterse** [comment]
Oga isn't likely to be faster at parsing than Nokogiri any time soon as Oga does a substantial amount of it in Ruby while Nokogiri offloads everything to libxml/C. The claim in the README is meant to be something like "Taking everything into account, if Oga is not fast enough ...", I'm not sure how I can better describe that. Alternatively I can just remove it to avoid confusion.

**Comment by Zapotek** [comment]
That's fair enough, thanks for the clarification.

**Comment by YorickPeterse** [comment]
I clarified this a bit in 00ab8bbe73e6c28921fa9ac0c3e54eddfcecd20c.
