### ISSUE TITLE
xml declaration inside the html body

### ISSUE THREAD

**Issue by Junyulive** [YorickPeterse/oga#163]
I have some old html content, it contains a xml declaration, this will cause exception when parse_html. Some old site contains these tags when copy/paste content from micrsoft office such as word/frontpage etc.

Do you think Oga should ignore xml declaration inside html body when parse_html specifically? 

```
<html>
<head>
</head>
<body>
  <h1> header </h1>
  <p> 
    <h3> content </h3>
    <?xml:namespace prefix=o ns="urn:schemas-microsoft-com:office:office" /><o:p></o:p>
  </p>
</body>
</html>
```

**Comment by YorickPeterse** [comment]
@Junyulive As far as I'm aware `<?xml:namespace prefix=o ns="urn:schemas-microsoft-com:office:office" />` isn't even a valid XML declaration, or processing instruction. These are supposed to end with `?>` and not `/>`. Is this part of the XML/HTML specification, or is this some extension Microsoft added on top of things?

**Comment by Junyulive** [comment]
I didn't find it in the specification, I guess it added by microsoft when copy some office data to the html editor. 

Browser and html editor will ignore these invalid tags, because of the html nature, is it possible to make Oga.parse_html more compatible for html.

**Comment by YorickPeterse** [comment]
@Junyulive Since SGML supports `<?foo >` I suspect this is some twisted extension of that. I'm not strictly opposed to supporting this, I'd just like to know where this is documented (if at all) so I can see if there are any further cases to take care of.

Having said that, if this is some Microsoft Office specific crap not covered by any official specifications I'm not sure if I want to support it. It's a slippery slope to having to support all kinds of twisted extensions.

**Comment by YorickPeterse** [comment]
@Junyulive How crucial is support for this particular tag to your workflow? I have thus far been unable to figure out if this particular tag is using some kind of official syntax or not. It's starting to look like this might just be libxml/Nokogiri's error handling that results in this tag being parsed.

**Comment by Junyulive** [comment]
I think it's the nature of html which doesn't have strict tag formation, so html may contains a xml declaration or other weird tags. 

Browser and Nokogiri just parsed these html successfully, so I think we should have these compatibility when parse html specifically in Oga.

The known valid xml declaration doesn't work as well.

```
<html>
<head>
</head>
<body>
  <h1> header </h1>
  <p> 
    <h3> content </h3>
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  </p>
</body>
</html>
```

**Comment by Junyulive** [comment]
I found another example in my project. I was parsing various html from the internet.
`<span ;="">content</span>`
Works in Nokogiri, he just ignore these invalid attributes and let the parse through. Like you said above the way of their error handling make more sense in a parser app. You may provide an addition options allow error raise, but by default just ignore these invalid tags.

**Comment by YorickPeterse** [comment]
@Junyulive 

> The known valid xml declaration doesn't work as well.

I fixed this in 116b9b0ceb6feab4daa0bb417302590fba948bef.

> I think it's the nature of html which doesn't have strict tag formation, so html may contains a xml declaration or other weird tags.

I'm not sure about this. Nokogiri's behaviour is rather odd:

    Nokogiri::HTML.fragment('bar') # => "<foo>bar</foo>"
    Nokogiri::HTML.fragment('<?cookies a="b" -->text here').to_html # => "<?cookies a=\"b\" -->text here" (parsed as a processing instruction)

There are probably a few more examples, but it seems Nokogiri/libxml only closes things properly for a specific set of tags opposed to just closing whatever is opened the moment it finds any kind of closing tag.

Personally I feel uneasy about adding support for parsing nodes that can be closed with basically any kind of closing tag. Doing so will lead to a parser that's a nightmare to maintain. I _can_ add support for closing a processing instruction with `/>`, but where does it stop? Should Oga also support comment/cdata/doctype/whatever closing tags? If so, to what extends may that break compatibility according to the XML/HTML specification?

> I found another example in my project. I was parsing various html from the internet.

This is a separate problem, please create a new issue for that.

**Comment by YorickPeterse** [comment]
Come to think of it, I'll just add support for closing a processing instruction with `/>` and `>` and we'll see how messed up things get over time.

**Comment by YorickPeterse** [comment]
Further digging this seems to be an HTML special "feature" of libxml, the XML parser does not support closing processing instructions using `/>` as far as I can tell.

**Comment by YorickPeterse** [comment]
I'm going to close this for the time being. It's not clear if this input is HTML, XML, SGML, or some weird extension to either of these formats. It's also not clear what the parsing rules would be, e.g. would there be other closing tags as well?

This issue can be re-opened once there is enough interest and the specifications are more clear.
