### ISSUE TITLE
Severe: to_xml drops closing tags on empty elements when rendering HTML

### ISSUE THREAD

**Issue by scotchi** [YorickPeterse/oga#165]
Since 2.4 Oga drops closing tags on HTML documents when rendering.  This can obviously result in very broken documents.

    Oga.parse_html('<html></html>').to_xml
    -> <html>

    Oga.parse_html('<html><head></head></html>').to_xml
    -> <html><head></html>

Or, more to the point (closer to the actual case in the wild where I ran into this):

    Oga.parse_html('<div id="a"></div><div id="b">foo</div>').to_xml
    -> <div id="a"><div id="b">foo</div>

In that last case, content that is part of the second div gets moved to be inside of both.

**Comment by YorickPeterse** [comment]
@scotchi Commit e0e0687dc29427c854c9fa6d3c19cee1c04f92c7 should solve this problem. Could you test this commit using your code and report back if this solves your problem?

**Comment by scotchi** [comment]
Yes, it does seem to resolve the issue in the actual application.

**Comment by YorickPeterse** [comment]
The fix for this is available in Oga 2.7 which is now on RubyGems.
