### ISSUE TITLE
Warnings in generated files

### ISSUE THREAD

**Issue by bryanp** [YorickPeterse/oga#166]
I've started running my gem's test suite with warnings turned on, and Oga is causing noise. Took a stab at resolving the warnings, and most are easy but I'm not sure the best way to resolve the warnings in generated files like `lib/oga/xpath/lexer.rb`. 100% of them are indentation problems.

This would be a non-issue if the warnings weren't generated at runtime. I'd rather not silence warnings for every call to Oga unless there's no other option. Let me know what you think!

**Comment by YorickPeterse** [comment]
@bryanp The output is generated by Ragel and there's no way to reliably control the indentation. It's not worth the time and effort to hack some kind of code re-indentation system in just so `ruby -W2` doesn't spit out indentation warnings.

**Comment by bryanp** [comment]
Fair enough, I just silenced the warnings since we only use Oga in one place.
