### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8 from node_set method

### ISSUE THREAD

**Issue by marcamillion** [YorickPeterse/oga#167]
I am attempting to crawl this URL: http://www.johnvanderlyn.com and parse the body for text, like so:

```ruby
 def get_page
    body = Net::HTTP.get(URI.parse(@url))
    document = Oga.parse_html(body)
  end

document = get_page    
words = document.css('body').text
```

When I get this error:

`/gems/oga-2.7/lib/oga/xml/node_set.rb:276:in block in text': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)`

That is related to this [bit of code here](https://github.com/YorickPeterse/oga/blob/master/lib/oga/xml/node_set.rb#L271-L281).

I am not quite sure why it is throwing that error and can't make heads or tails of it.

Thoughts?

**Comment by YorickPeterse** [comment]
Oga relies on Ruby's default encoding whenever it uses strings, which is UTF-8. The website's content in turn contains data that is not valid when encoded in UTF-8.

The easiest way of dealing with this is to convert the input to UTF-8 before parsing while removing anything that is not valid in UTF-8. Something like this should do the trick:

```
body = Net::HTTP.get(URI.parse(@url))
document = Oga.parse_html(body.encode('UTF-8', invalid: :replace, undef: :replace, replace: ''))
```

The rationale for Oga not doing anything specific with encodings can be found here: https://github.com/YorickPeterse/oga/issues/29#issuecomment-55639786

**Comment by YorickPeterse** [comment]
It's worth mentioning this isn't specifically about UTF-8. If you were to use a different default encoding you could run into the same problem. In other words, the input documents must be compatible with your Ruby's default encoding.

**Comment by marcamillion** [comment]
Thanks for the reply @YorickPeterse. 

Before you replied though, I actually discovered that out. So this solution worked for me:

    body = Net::HTTP.get(URI.parse(@url)).force_encoding 'UTF-8'

Similar to yours, but a bit simpler. 

Out of curiosity, is there anything my version may miss that yours doesn't?

**Comment by YorickPeterse** [comment]
@marcamillion Your version doesn't actually re-encode the data. `String#force_encoding` merely sets a flag indicating the encoding. Sometimes this may achieve the same results, sometimes it will produce garbage.

For example, let's take the Japanese word for "cat": ネコ

If we encode this as UTF-16 and then force encode it to UTF-8 we'll get garbage:

```ruby
"ネコ".encode('UTF-16').force_encoding('UTF-8') # => "\xFE\xFF0\xCD0\xB3"
```

On the other hand, if we use `encode` we'll get the right data:

```ruby
"ネコ".encode('UTF-16').force_encoding('UTF-8') # => "ネコ"
```
