### ISSUE TITLE
Oga.parse_html raises undefined method 'node_set=' for Oga::XML::Doctype

### ISSUE THREAD

**Issue by pcasaretto** [YorickPeterse/oga#169]
Input:

Running `Oga.parse_html` on 

```
<div align="center"><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
</body>
</html> 
```

fails with:

```
NoMethodError: undefined method `node_set=' for #<Oga::XML::Doctype:0x0055bafe2673e8>
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node_set.rb:298:in `take_ownership'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node_set.rb:48:in `block in initialize'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node_set.rb:45:in `each'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node_set.rb:45:in `each_with_index'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node_set.rb:45:in `initialize'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node.rb:54:in `new'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/node.rb:54:in `children='
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/parser.rb:334:in `on_element_children'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/parser.rb:469:in `_rule_23'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/xml/parser.rb:229:in `each_token'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/oga.rb:23:in `parse'
	from /usr/local/bundle/gems/oga-2.7/lib/oga/oga.rb:23:in `parse_html'
```

It seems that the doctype inside the div is causing the problem.

**Comment by YorickPeterse** [comment]
This happens because Oga tries to set the next node for the doctype. Since a doctype is not a regular node this will error. There was a similar problem involving XML declarations, which was resolved in 116b9b0ceb6feab4daa0bb417302590fba948bef. For XML declarations this made sense since they're basically processing instructions, but I'm not sure what the best approach would be for doctypes.

**Comment by pcasaretto** [comment]
In any case, Am I right to assume it should not raise an exception whatever the input is.
Would checking what nokogiri does with this help?

**Comment by YorickPeterse** [comment]
@pcasaretto 

> In any case, am I right to assume it should not raise an exception whatever the input is?

No. Oga does not guarantee it will never raise an exception when parsing input. However, it should not raise an error for this particular example.

> Would checking what nokogiri does with this help?

Not really, since Nokogiri is a separate project.

**Comment by pcasaretto** [comment]
Got it. How can I help?

**Comment by YorickPeterse** [comment]
@pcasaretto The main problem here is that I'm not really sure what the path forward is from a design perspective. For example, an easy solution would be to e.g. make `Doctype` inherit from `Node`. This however is weird because doctypes can not have child nodes, which `Node` will make possible. At the same time I think you should be able to take a doctype, then request the previous/next node whatever they may be.

**Comment by pcasaretto** [comment]
> Oga does not guarantee it will never raise an exception when parsing input

Are there known cases where this will happen?

> This however is weird because doctypes can not have child nodes

I understand that they should not, semantically. But from my (biased and limited) perspective, I expected Oga not to "enforce" that, the same way that it does not "enforce" valid html like automatically adding closing tags.

**Comment by pcasaretto** [comment]
So I should always protect the parse call with a rescue clause when reading user input.
And that makes total sense. Regardng this particular case, in my mind, a node is a node. Some nodes are expected not to have children but I don't think Oga should treat them differently than other nodes.
But like I said, I trust your judgement a lot more than mine.

**Comment by pcasaretto** [comment]
Thanks! Sorry I could'nt make myself more useful.

**Comment by YorickPeterse** [comment]
@pcasaretto No problem!
