### ISSUE TITLE
outputting html empty elements

### ISSUE THREAD

**Issue by gittmaekawa** [YorickPeterse/oga#170]
I guess this isn't good question to ask here, but I couldn't find any information about this at other web pages.
I want to parse and output HTML.  For example, if there is a string such as `<div>aaa</div>`  I want to be able to parse it then output a string as `<div>aaa</div>`.

I know Oga is pretty good to parse HTML. But to output, in some cases, oga isn't enough. For example I can't output empty elements like `<img>` without slash. The output of `<img>` using `#to_xml`  is `<img/>`, not `<img>`, because it is rendered as XML.   

How can I solve this problem?
Or, if I can't, are there any plans to add #to_html like nokogiri?  Is it better if I can add it to Oga and ask to pull it? (although I'm not sure that I can hack Oga...)

**Comment by YorickPeterse** [comment]
Currently there's no way around this, Oga will always use `/>` even when not strictly necessary. However, this is valid HTML4/XHTML/HTML5 so it shouldn't be a problem.

Changing this would be fairly easy. In `Oga::XML::Generator#on_element` an extra check would have to be added to omit the `/` for certain self closing HTML5 elements (those listed in `HTML_VOID_ELEMENTS`).
