### ISSUE TITLE
outputting void element as a html doesn't work when the elements are manually created.

### ISSUE THREAD

**Issue by TakanobuMaekawa** [YorickPeterse/oga#171]
Thanks for #170.  That was helpful.
However I encountered an another problem. I'm not sure but this may be related to #170.

Here is the output of IRB:

```
$ bundle list
...
...
* oga (2.9)

$ irb
Oga::XML::Element.new(name: 'img').html?
false
Oga::XML::Element.new(name: 'img').to_xml
"<img />"
```

As you see, oga can't remove the slash when a void element is manually created.
I can't say this is a bug or not. If I missed some settings, please tell me.
Otherwise,  I will also appreciate  if I can know where to change in oga. I'll try it.

**Comment by YorickPeterse** [comment]
Oga only knows whether it's dealing with HTML or XML elements when elements reside in an `Oga::XML::Document` with `type` set to either `:xml` or `:html`. Without this there's no way of knowing if `/>` or `>` should be used.
