### ISSUE TITLE
Weird website problems

### ISSUE THREAD

**Issue by rtfpessoa** [YorickPeterse/oga#172]
Hi,

I am parsing one website which contains invalid HTML (at least I think so).

In `<td><1.0.4&nbsp;>=1.0.0-beta.0</td>`, as you can see, the contents of the `td` are not escaped and for that reason Oga cannot give me the right `.text` that it contains.

Chrome handles this smoothly by converting it to `<td>&lt;1.0.4&nbsp;&gt;=1.0.0-beta.0</td>`.
Is there any flag I can use in Oga to fix this?

**Comment by YorickPeterse** [comment]
No, there is no such flag. I don't see a way to support this either as Oga starts processing text as element names the moment it runs into an unescaped `<`. The only way around this is to ensure the website's output is encoded/escaped properly.
