### ISSUE TITLE
Element#attribute does not return correct result with Symbol input

### ISSUE THREAD

**Issue by PikachuEXE** [YorickPeterse/oga#173]
In [doc](http://code.yorickpeterse.com/oga/latest/Oga/XML/Element.html#attribute-instance_method)
The input mentioned supporting `String` AND `Symbol`

But by testing and looking through the source code
It never returns the attribute if symbol is passed to the method

The internal method [`attribute_matches?`](https://github.com/YorickPeterse/oga/blob/master/lib/oga/xml/element.rb#L350) does not convert symbols to strings
And neither the [`attribute` method](https://github.com/YorickPeterse/oga/blob/master/lib/oga/xml/element.rb#L66)

**Comment by YorickPeterse** [comment]
`Oga::XML::Element#split_name` takes care of casting data to a string: https://github.com/YorickPeterse/oga/blob/e9953d4212269237c3c034978dc6bf2492488d81/lib/oga/xml/element.rb#L341. However, this method is not called for HTML documents, meaning Symbols are not working there.
