### ISSUE TITLE
Improve XPath namespace support

### ISSUE THREAD

**Issue by leejarvis** [YorickPeterse/oga#176]
The README demonstrates somewhat cumbersome [namespace support](https://github.com/YorickPeterse/oga#namespace-support). I'm wondering if there are any plans to improve the XPath API to increase the fluidity of parsing namespace heavy XML documents. You mention in the README:

> In the future I might add an API to ease this process, although at this time I have little interest in providing an API similar to Nokogiri.

Which is a fair comment. I'm wondering if you had an alternative API in mind? I think the Nokogiri API is quite nice, and the only alternative I can think of is to dynamically update a list of supported namespace within the document itself, which I don't really think is any nicer.

## Example

Take the following (contrived) XML:

```xml
<main:library xmlns="http://example.com" xmlns:main="http://example.com/library">
  <main:name>The library</main:name>

  <bs:bookshelf xmlns:bs="http://example.com/author/lee">
    <bs:name>Lee's books</bs:name>
  </bs:bookshelf>

  <bs:bookshelf xmlns:bs="http://example.com/author/yorick">
    <bs:name>Yorick's books</bs:name>
  </bs:bookshelf>
</main:library>
```

We're interested in all of the `name` attributes. Here's how we might parse them in Nokogiri:

```ruby
require "nokogiri"

doc = Nokogiri.XML(DATA.read)

# auto registered namespace aliases
p doc.at_xpath("//main:name").text #=> "The library"

namespaces = {
  lee: "http://example.com/author/lee",
  yorick: "http://example.com/author/yorick",
}

p doc.at_xpath("//lee:bookshelf/lee:name", namespaces).text       #=> Lee's books
p doc.at_xpath("//yorick:bookshelf/yorick:name", namespaces).text #=> Yorick's books

```

Any alternative Oga implementation as suggested by the README would be non-trivial.

My suggestion would be to provide an alternative API to Nokogiri. Happy to discuss to any caveats around that idea.

Any thoughts?

**Comment by YorickPeterse** [comment]
This could probably be done by having the XPath compiler compile queries such as `lee:bookshelf` into `*:bookshelf[namespace-uri() = "http://example.com/author/lee"]`. This however means that we need to make sure that the compiled code is bound to not just the input query `lee:bookshelf`, but also the namespaces aliases; otherwise the same query with different aliases would run the same Ruby code.

I'm thinking something like this could work:

```ruby
doc = Oga.parse_xml('document here', aliases: { lee: 'http://....', yorick: '...' })

doc.at_xpath('lee:bookshelf')
```

**Comment by YorickPeterse** [comment]
An alternative would be to pass the aliases to every Proc compiled for an XPath query, then have the Proc do a Hash lookup to figure things out. This however is a bit hairy to implement, and will probably come with a runtime cost.

**Comment by YorickPeterse** [comment]
For caching currently the XPath AST is used. I think it's possible to change this to e.g. `[xpath-ast, alias-hash]`, skipping `alias-hash` if not defined (so we don't insert empty hashes into the cache).

**Comment by leejarvis** [comment]
> I'm thinking something like this could work:

The issue with a document wide alias list is that it presumes one knows these aliases upfront. This becomes an issue when you want to dynamically look up elements for a given namespace. An example might be when parsing a WSDL with namespace'd types:

```xml
<x:root xmlns:x="http://example.com">
  <x:schema xmlns:foo="http://example.com/types">
    <x:complexType>
      <x:element name="myElement" type="foo:MyType">
        <!-- ... !>
      </x:element>
    </x:complexType>
  </x:schema>
  <x:schema targetNamespace="http://example.com/types">
    <x:simpleType name="MyType">
      <!-- ... !>
    </x>
  </x:schema>
</x:root>
```

Here, element `myElement` references `foo:MyType`, which might be different to `bar:MyType`. We would pull out the correct type dynamically by looking up the referring `targetNamespace`. 

> An alternative would be to pass the aliases to every Proc compiled for an XPath query, then have the Proc do a Hash lookup to figure things out. This however is a bit hairy to implement, and will probably come with a runtime cost.

This is where I started too. I also presumed there would be some runtime cost.

**Comment by YorickPeterse** [comment]
@leejarvis So if I'm understanding correctly you want to:

1. Dynamically generate these aliases based on some WSDL
2. The WSDL/list of aliases is not available _before_ parsing the document

Is that correct?

**Comment by leejarvis** [comment]
Actually I just realised my previous example doesn't really make much sense, since it's different from namespace aliases. To retrieve `MyType` from `myElement` you would parse `foo` from `type` and then fetch the namespace from `schema.namespaces` which Oga already parses, and then `MyType` can be fetched by targeting `targetNamespace`.

So I think this is just about namespace aliases in static terms, and your suggestion of a document-wide  alias hash would actually be fine.

> The WSDL/list of aliases is not available before parsing the document

This is technically correct. A full list of aliases isn't available until you parse the document (programatically or merely browsing it). But I think it doesn't really matter for the XPath parser. The parser only needs to know about aliases that we're already aware of, since those are what we'll use to parse the XML with static XPath queries.

**Comment by YorickPeterse** [comment]
This has been moved to https://gitlab.com/yorickpeterse/oga/issues/176
