### ISSUE TITLE
Feature Request: work on :to_json for converting HTML and XML to json with one method

### ISSUE THREAD

**Issue by mistergibson** [YorickPeterse/oga#183]
Dear Yorick,

I was hoping that you could look at adding a :to_json method.

I'd like to do the following:

::Oga::parse_html(response.body).to_json

... and get a JSON formatted string containing every type, name, attribute, and content of each html element in the response.body.

Thanks

**Comment by YorickPeterse** [comment]
What is the use case for this, and why would it be so important to include this in Oga itself instead of it being provided as a third-party library by someone else?

**Comment by mistergibson** [comment]
I was thinking of passing the output to a web page where JavaScript would process the JSON

**Comment by YorickPeterse** [comment]
I'm going to close this, for two reasons:

1. I don't think the use case warrants adding this to Oga
2. There's no generic way of representing XML in JSON. For example, comments can't be expressed in JSON. I also don't want to invent a structure to represent XML as JSON as at that point you should just use _either_ XML or JSON.
