### ISSUE TITLE
Feature Request: add method to ::Hash - to_xml to covert ::Hash to xml data.

### ISSUE THREAD

**Issue by mistergibson** [YorickPeterse/oga#184]
I don't know how you feel about augmenting standard kernel classes, but this would be very handy. I'm currently using xml-simple and don't feel it is outputting proper xml - particularly where ::Array are concerned. What do you say?

**Comment by YorickPeterse** [comment]
Monkey patching standard library classes isn't something that belongs in Oga. Further, how would you provide a generic implementation of this? What should happen when running ` { a: 10 }.to_xml`?

Oga's goal is to provide a library for parsing XML/HTML and querying it, it's not a generic "convert to/from XML" library.
