### ISSUE TITLE
Syntax Error Handling

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#20]
Oga should be capable of dealing with invalid XML/HTML up to a certain extend. To deal with this an input correction system would have to be implemented at the lowest level possible. 

Initially I thought about implementing this between the lexer and the parser. The problem however is is that tokens from the lexer are emitted one by one instead as a whole. As a result of this you can not keep track of what context you're currently in without hindering performance. An alternative solution is to do this on parser (Racc) level.

Regardless of where it takes place this system should be capable of correcting most common mistakes. However, I don't want to sacrifice too much for the sake of forgiving invalid input. In other words, there has to be a balance between forgivingness and correctness.

**Comment by khoan** [comment]
currently, failing for [ill formatted feed](https://gist.github.com/khoan/7e6659eb2e4a0dedafec) (newline feed after <rss version="2.0"). The same xml passes [w3schools.com](http://www.w3schools.com/xml/xml_validator.asp) validator.

my 2cents, a good balance: whatever passes on w3school should pass as valid xml

**Comment by YorickPeterse** [comment]
@khoan Said XML parses fine when using the master branch and the latest Gem release (0.2.3). The particular problem wasn't caused due to lack of syntax error handling of sorts, but due to the problem described in #58.

**Comment by khoan** [comment]
@YorickPeterse, you're right. Looks like gist converted all the windows line feed characters into unix newline. I've now put a failing sample into git.

```ruby
$ cat oga_test
#!/usr/bin/env ruby

require 'oga'
require 'open-uri'

class ElementNames
  def on_element(namespace, name, attrs={})
    puts namespace.inspect
    puts name.inspect
    puts attrs.each(&:to_xml)
  end
end

handler = ElementNames.new

parser = Oga::XML::SaxParser.new(
  handler, 
  open('https://raw.githubusercontent.com/khoan/rPad/master/googleshopping_1.xml').read
)
parser.parse
```

**Comment by YorickPeterse** [comment]
@khoan Are these Windows line endings as in `\r\n` or just `\r`? The lexer currently doesn't handle the latter (https://github.com/YorickPeterse/oga/blob/31764593070b29fcd16040a6a0bd553e464324cd/ext/ragel/base_lexer.rl#L49) so that might explain the problem.

**Comment by khoan** [comment]
according to [ascii table](http://ascii-table.com/control-chars.php) control+m is carriage return. So I believe it's ```\r```

ah, so in theory, all that's required is to add control+m as a newline in the lexer.

**Comment by YorickPeterse** [comment]
@khoan Could you open a separate issue for this?

**Comment by khoan** [comment]
done: #89

**Comment by YorickPeterse** [comment]
Closing this one as this should be taken care of (for the most part) by 13e2c3d82ffb9f32b863cb47f6808cf061e07095. Other cases not yet handled should be reported as a separate issue whenever they occur.
