### ISSUE TITLE
Look into supporting character/entity reference support

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#68]
The character/entity references discussed in http://www.w3.org/TR/REC-xml/#sec-references should probably be supported. An example in Ox: https://github.com/ohler55/ox/blob/3764d26ab44f3202508a0b5ef2f9944b68bfef75/test/tests.rb#L314-L319

**Comment by YorickPeterse** [comment]
Looking into this again as I need support for a bunch of entities (e.g. `&nbsp;`). The htmlentities Gem doesn't seem to support all entities so that's not really an option, for example:

```ruby
HTMLEntities.new.decode('&boxvr;') # => "&boxvr;"
```

which is supposed to give back:

```ruby
[9500].pack('U') # => "├"
```

As an alternative I'll probably use this list: https://gist.github.com/YorickPeterse/fe37e80c271b3e94f3d7

One downside is that this will likely slow down the parsing/serialization process quite a bit as the code has to iterate over every Hash value and at minimum check if a value is present (saving unneeded string allocations of `String#gsub`).

**Comment by jrochkind** [comment]
Can it be an option only by default turned on for HTML?  In XML, you can watch for fewer named entities... oh, but I guess you still need to handle numeric entities. Not sure if it'll actually be any faster to restrict to only what you need for XML. 

But automatically un-escaping HTML named entities in XML might even be incorrect? Gets confusing to reason about, not sure.

**Comment by YorickPeterse** [comment]
The big list in the Gist would indeed only be used for HTML documents. This ensures the performance penalty only applies to HTML documents, but I'd still prefer for it not to be that much slower than it currently is.

**Comment by jrochkind** [comment]
Is there a way to turn the Hash into an actual parser/lexer, so you don't need to iterate over all the keys? In theory, if you encounter `&` followed by a letter that doesn't begin _any_ of them, you can stop. Otherwise, continue with second letter, etc. 

Compiling it into a giant regexp union might  have the same effect, and also be faster than iterating through every key.

**Comment by YorickPeterse** [comment]
The fastest way would be to embed the conversion of entities to their "true" form in the lexer. This is one of the ideas I have, but since the lexer code is shared between C and Java it's not as trivial to implement as one might hope. The idea I have is basically as following:

1. In the state machine used for processing text/attribute values a rule for every entity will be added
2. Said rule will append the entity to some internal array
3. When generating the tokens for attribute values and/or element text the Ruby code checks this array and _only_ converts the entities that were found

This process would remove the need for iterating over the entire set. The annoying part is that I'd have to duplicate the entity mapping in 3 places:

1. In Ruby so certain characters can be converted back into entities
2. In the XML lexer's "text" state machine (used for element text)
3. In the XML lexer's "string" state machine (used for attribute values)

I'm not sure if Ragel allows me to include other grammars into the body of a state machine, or only at the top level. If this is possible I could move the entity handling to a separate file and include it in both the mentioned state machines.

**Comment by YorickPeterse** [comment]
Note to self: this system should ensure that any entities that appear in a `<style>` or `<script>` tag are _not_ converted. In other words, the input `<style>&amp;</style>` should stay as is and _not_ be converted into `<style>&</style>`.

**Comment by YorickPeterse** [comment]
Thinking of this, it might actually make more sense to do this lazily in `Oga::XML::Text` and `Oga::XML::Attribute` instead of doing this on lexer/parser level. This has numerous benefits:

1. No performance overhead in the lexer/parser
2. Keeps the lexer as it is, making my life easier
3. Code such as `Oga::XML::Text.new(:text => '&quot;').text` would actually return `'"'` and not `'&quot;'`

Doing this post-parsing can be done in two ways:

1. Simply decode entities every time `Text#text` and/or `Text#to_xml` is called
1. Decode entities once when needed, then cache the result (basically overwriting `#text`)

The latter would have to be thread-safe as I do want to allow multiple-threads to read from a document/element without it blowing up. A mutex or a compare-and-swap operation should suffice, but it _shouldn't always_ lock as that will most likely slow things down.
