### ISSUE TITLE
XML::Text escapes Javascript when it shouldn't

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#79]
Example:

```
 $ pry -r oga
2.2.0p0 > element = Oga::XML::Element.new(:name => 'script')
=> Element(name: "script")
2.2.0p0 > element.inner_text = '10 > 20'
=> "10 > 20"
2.2.0p0 > element.to_xml
=> "<script>10 &gt; 20</script>"
```

In case of `<script>` tags the output should not be escaped as this would produce invalid Javascript.

**Comment by YorickPeterse** [comment]
One way of solving this would be to introduce `to_html` which, for certain elements (based on the name), would alter the behaviour of `to_xml`. That is, `to_html` would simply be an alias for `to_xml` in most cases, except for `XML::Element` nodes with the name set to `script`.

**Comment by YorickPeterse** [comment]
Super dirty patch for option 2:

```ruby
module Oga
  module XML
    class Text < CharacterNode
      def to_xml
        if parent.name == 'script' and root_node.type == :html
          return super
        else
          return Entities.encode(super)
        end
      end
    end # Text
  end # XML
end # Oga
```

**Comment by YorickPeterse** [comment]
Relying on `to_html` instead of `to_xml` probably makes more sense as there will likely be other cases where dumping HTML differs from dumping XML.

**Comment by YorickPeterse** [comment]
Note to self: the above snippet should take into account that text nodes can also be embedded into cdata nodes, in such a case it should continue traversing the document tree upwards until it finds the first parent element.

**Comment by jrochkind** [comment]
I'm not sure this is really true.... 

I think

<script> element.inner_text = '10 > 20'</script> is actually invalid HTML, isn't it?  There is no special rule that says you can have un-escaped angle brackets inside a `<script>` block, I don't think?

Googling to try to figure it out, it gets confusing fast. Which is one reason people prefer linked script file instead of inline, I think! But here's one stackoverflow on it: http://stackoverflow.com/questions/8749001/escaping-html-entities-in-javascript-string-literals-within-the-script-block

**Comment by YorickPeterse** [comment]
@jrochkind It's valid HTML, or at least HTML5. On top of that both Firefox and Chromium handle this case just fine, so does libxml/Nokogiri. As a result I kinda have to support this, that and I bumped into this specific problem in a production application of myself.

**Comment by YorickPeterse** [comment]
Having said that, including a literal `</script>` tag inside another `</script>` tag (e.g. as a string literal) is _not_ valid and will indeed break various browsers and other existing parsing libraries. A Nokogiri example:

```
2.2.0p0 > Nokogiri::HTML.fragment('<script>"</script>"</script>')
=> #(DocumentFragment:0x3fdb99471210 {
  name = "#document-fragment",
  children = [ #(Element:0x3fdb99470f54 { name = "script", children = [ #(CDATA "\"")] }), #(Text "\"")]
  })
```
