### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by Arcovion** [YorickPeterse/oga#83]
I am really struggling with the `xpath`/`css` methods, I looked for some examples and [found this from your blog](http://yorickpeterse.com/articles/oga-a-new-xml-and-html-parser-for-ruby/):
```ruby
require 'oga'
require 'net/http'

body     = Net::HTTP.get(URI.parse('http://www.reddit.com/'))
document = Oga.parse_html(body)
titles   = document.xpath('//div[contains(@class, "entry")]/p[@class="title"]/a/text()')

titles.each do |title|
  puts title.text
end
```
Which isn't working for me on Oga 0.2.3 with Windows or Linux; the document seems to parse correctly but `titles` is empty.
I checked the XPath in chrome and it still works:
`$x('//div[contains(@class, "entry")]/p[@class="title"]/a/text()')`
So I tried on Linux with Nokogiri and to my surprise it worked:
```ruby
require 'nokogiri'
require 'net/http'

body     = Net::HTTP.get(URI.parse('http://www.reddit.com/'))
document = Nokogiri::HTML(body)
titles   = document.xpath('//div[contains(@class, "entry")]/p[@class="title"]/a/text()')

titles.each do |title|
  puts title.text
end
```
What am I missing? Is there a bug in `xpath`/`css`?
Moreover, it'd be nice to see more simple examples like this for common use cases and show off all the features. Thanks.

**Comment by YorickPeterse** [comment]
This seems to be caused by Reddit assigning an explicit namespace to the `<html>` element (using `<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">` to be exact). As far as I can tell `http://www.w3.org/1999/xhtml` is the default namespace URI for XHTML/HTML5 so I'll see how I Oga can support this more easily.

Regarding the examples, there are a few already in the README (https://github.com/YorickPeterse/oga#examples) but I'll see if I can add any other useful ones.

**Comment by Arcovion** [comment]
I see, it just so happens the other two sites I was trying to parse have this namespace attr too.

For the examples I was just thinking of larger documents and real URLs as opposed to small snippets of local text which are in your specs/readme. E.g. an oft-used example for web crawlers is downloading xkcd comics:
```ruby
require 'oga'
require 'open-uri'

homepage = open 'http://xkcd.com', &:read
img_url  = Oga.parse_html(homepage).at_xpath 'string(//*[@id="comic"]/img/@src)'
img_name = File.basename img_url
img      = open img_url, &:read

File.write img_name, img, mode: 'wb'
```
This doesn't serve to describe Oga's features, but it's showing how you might use it and presents a more complicated XPath to show how powerful they are. I say this as some users may be unfamiliar with them - Python's popular [Beautiful Soup](http://en.wikipedia.org/wiki/Beautiful_Soup) library for example doesn't support XPaths! Personally I think they're the best way to parse HTML/XML and should be advertised as such.
Furthermore, examples like these are self-contained so they can be copied and pasted straight from the Readme like [Nokogiri's synopsis](https://github.com/sparklemotion/nokogiri#synopsis), this gives you a working example/walkthrough out of the box (which is what I looked for and found in your blog post).

**Comment by YorickPeterse** [comment]
Moving the namespace problem over to #85.
