### ISSUE TITLE
Parse error on Youtube

### ISSUE THREAD

**Issue by Arcovion** [YorickPeterse/oga#84]
```ruby
require 'oga'
require 'open-uri'

html = open 'https://www.youtube.com/watch?v=qp20Lh7o56M', ssl_verify_mode: 0, &:read
Oga.parse_html html
```
Is it acceptable to make issues for random websites that aren't being parsed correctly?
Here I get an exception for parsing [this url](https://www.youtube.com/watch?v=qp20Lh7o56M).
I'm just messing around with different websites, note that Nokogiri appears to be able to parse this site correctly.
Edit: I get the same error on Google and some other websites, I suppose Oga is not quite ready for web crawling yet. =[

**Comment by YorickPeterse** [comment]
There's no need for separate tickets, simply adding the links to this issue is enough. Having said that, there's https://github.com/YorickPeterse/oga/issues/20 which, when resolved, should take care of these problems.

**Comment by Arcovion** [comment]
Here's some from the top 100:
- [ ] https://google.com
- [ ] https://yahoo.com
- [ ] https://amazon.com
- [ ] https://yandex.ru
- [ ] https://linkedin.com
- [ ] https://www.ebay.com
- [ ] https://instagram.com
- [ ] https://vk.com

https://github.com/YorickPeterse/oga/issues/83#issuecomment-81768893 should address:
- [ ] https://reddit.com
- [ ] https://imgur.com

Looks like the vast majority of websites are ok though!

**Comment by YorickPeterse** [comment]
Using this script:

```ruby
require 'oga'
require 'httpclient'

# Silence HTTPClient warnings
class HTTPClient
  def warn(*); end
end

module WebAgent::CookieUtils
  def warn(*); end
end

http = HTTPClient.new

urls = DATA.each_line do |line|
  url  = line.strip
  body = http.get(url, :follow_redirect => true).body

  begin
    Oga.parse_html(body)

    puts "[OK]:    #{url}"
  rescue Exception => error
    puts "[ERROR]: #{url} => #{error.message}"
  end
end

__END__
http://google.com
http://yahoo.com
http://amazon.com
http://yandex.ru
http://linkedin.com
http://www.ebay.com
http://instagram.com
http://vk.com
http://reddit.com
http://imgur.com
```

The output is as following:

```
[OK]:    http://google.com
[ERROR]: http://yahoo.com => Unexpected T_STRING_DQUOTE, expected element closing tag instead on line 87
[ERROR]: http://amazon.com => Unexpected T_STRING_DQUOTE, expected element closing tag instead on line 1861
[ERROR]: http://yandex.ru => Unexpected end of input on line 1
[ERROR]: http://linkedin.com => Unexpected end of input on line 682
[ERROR]: http://www.ebay.com => Unexpected end of input on line 18
[ERROR]: http://instagram.com => Unexpected end of input on line 278
[ERROR]: http://vk.com => Unexpected end of input on line 20
[OK]:    http://reddit.com
[OK]:    http://imgur.com
```

I've checked off the websites that pass, the other ones probably use some HTML not supported yet by Oga.

**Comment by YorickPeterse** [comment]
Parsing support for Yahoo (the problem that broke it to be specific) was added in 6b779d788384b89ba30ef60c17a156216ba5b333.

**Comment by YorickPeterse** [comment]
Amazon.com taken care of in 73fbbfbdbdecafcf5f873b8a27e81c19a2e2ed0c.
