### ISSUE TITLE
xpath with large xml file

### ISSUE THREAD

**Issue by giuan** [YorickPeterse/oga#88]
With the cia factbook in xml if i try this
````ruby
doc.xpath("//country/field[@ref='f2004']")
````
it don't terminate (no error).
The code works with a smaller version of the factbook.

But these expressions work with the big file
````ruby
doc.xpath("/factbook/region/country/field[@ref='f2004']")
````
````ruby
doc.css("country field[ref='f2004']")
````
ruby 2.1 oga 0.2.3 mac

**Comment by YorickPeterse** [comment]
Could you provide a sample XML file that produces this? Chances are that the XML file is big enough for XPath evaluation to take a while (it's currently quite slow).

**Comment by giuan** [comment]
The XML is http://jmatchparser.sourceforge.net/factbook/data/factbook.xml.gz

````ruby
require 'oga'
require 'benchmark'

handle = File.open('factbook.xml')

doc = nil
puts "parse_xml"
puts Benchmark.measure {doc = Oga.parse_xml(handle)}

puts "factbook > region > country > field[ref='f2004']"
puts Benchmark.measure {
  elems = doc.css("factbook > region > country > field[ref='f2004']")
  puts elems.size
}

puts "css country field[ref='f2004']"
puts Benchmark.measure {
  elems = doc.css("country field[ref='f2004']")
  puts elems.size
}

puts "/factbook/region/country/field[@ref='f2004']"
puts Benchmark.measure {
  elems = doc.xpath("/factbook/region/country/field[@ref='f2004']")
  puts elems.size
}

puts "//country/field[@ref='f2004']"
puts Benchmark.measure {
  elems = doc.xpath("//country/field[@ref='f2004']")
  puts elems.size
}
````
````
parse_xml
  5.000000   0.140000   5.140000 (  5.209589)
css: factbook > region > country > field[ref='f2004']
232
  3.550000   0.140000   3.690000 (  3.715155)
css: country field[ref='f2004']}
232
  4.270000   0.100000   4.370000 (  4.419504)
/factbook/region/country/field[@ref='f2004']
232
  1.090000   0.010000   1.100000 (  1.130438)
//country/field[@ref='f2004']
after an hour no response
````
I tried with jruby 1.7.16 same problem

**Comment by YorickPeterse** [comment]
> I think that css "country field[ref='f2004']" is similar to "//country/field[@ref='f2004']".

No, this translates to `descendant::country/descendant::field[@ref="f2004"]`.

**Comment by giuan** [comment]
I tried with nokogiri.
The result:
````
parse_xml
  0.330000   0.070000   0.400000 (  0.410540)
factbook > region > country > field[ref='f2004']
232
  0.150000   0.000000   0.150000 (  0.144159)
/factbook/region/country/field[@ref='f2004']
232
  0.120000   0.000000   0.120000 (  0.130721)
descendant::country/field[@ref='f2004']
232
  0.150000   0.000000   0.150000 (  0.150887)
//country/field[@ref='f2004']
232
  0.150000   0.000000   0.150000 (  0.150868)
css country field[ref='f2004']
232
310.580000   1.670000 312.250000 (324.329383)
````
Nokogiri has the same problem with css

**Comment by YorickPeterse** [comment]
@giuan The last few releases of Oga contain various performance improvements that should make XPath evaluation quite a bit faster. Could you give the latest release (0.3.3) a try to see how things perform now?

**Comment by giuan** [comment]
With 0.3.3   ruby 2.2.1.
The file is 9.1MB
20%-30% better. Good!
````
parse_xml
  4.290000   0.140000   4.430000 (  4.525548)   old (  5.209589)

factbook > region > country > field[ref='f2004']
232
  3.500000   0.070000   3.570000 (  3.601097)   old (  3.715155)

css country field[ref='f2004']
232
  3.000000   0.010000   3.010000 (  3.036254)  old (  4.419504)

/factbook/region/country/field[@ref='f2004']
232
  0.870000   0.000000   0.870000 (  0.870964)  old (  1.130438)

descendant::country/descendant::field[@ref='f2004']
232
  3.020000   0.010000   3.030000 (  3.050675)  
//country/field[@ref='f2004']
after an hour no response

````

**Comment by YorickPeterse** [comment]
What is the output of the benchmark using the latest Oga? As far as I can tell it looks like you've shared the same output as mentioned in https://github.com/YorickPeterse/oga/issues/88#issuecomment-84624815.

**Comment by giuan** [comment]
parse_xml
  4.290000   0.140000   4.430000 (  4.525548)   old (  5.209589)

old (  5.209589) is the total time with oga 0.2.3

**Comment by YorickPeterse** [comment]
Ah ok, I missed that. I'll keep this issue open since there are several more changes I'd like to apply to make things faster.

**Comment by giuan** [comment]
I think that it's difficult to make things a lot faster. Nokogiri is almost C (right?) and it's 10x faster than oga, but it's normal for C vs Ruby.
I know that you work on Rubinius. The numbers are bad.
After 3 iteration in version 2.5.2:
````
parse_xml
 19.324621   0.305672  19.630293 ( 20.220511)
factbook > region > country > field[ref='f2004']
232
 10.253330   0.101667  10.354997 ( 10.730601)
css country field[ref='f2004']
232
 11.223590   0.105031  11.328621 ( 11.514171)
/factbook/region/country/field[@ref='f2004']
232
  2.036197   0.014075   2.050272 (  2.127982)
descendant::country/descendant::field[@ref='f2004']
232
  8.470855   0.059776   8.530631 (  8.921993)
````

**Comment by YorickPeterse** [comment]
Correct, Rubinius performance is not yet where I want it to be. In general the XPath evaluator _is_ quite slow with a lot of optimization possibilities. I can't make it faster than Nokogiri, but I can definitely make it faster than the current performance.
