### ISSUE TITLE
XML/HTML entities in attribute values are no longer decoded

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#91]
This is caused by the conversion happening in a lazy manner, which has only been implemented for `XML::Text#text`. Example:

```
Oga.parse_html('<p class="&nbsp;"></p>')
=> Document(
  children: NodeSet(Element(name: "p" attributes: [Attribute(name: "class" value: "&nbsp;")]))
)
```

**Comment by krasnoukhov** [comment]
Good catch, I ran into this like yesterday, but forgot to report. See failing sax-machine build, if you're interested: https://travis-ci.org/pauldix/sax-machine/jobs/57151728

**Comment by krasnoukhov** [comment]
I still see non-decoded entities in attributes as well as text/cdata when using SAX parser. Does that mean that I have to decode these manually?

**Comment by YorickPeterse** [comment]
@krasnoukhov Good catch, since this is handled in instances of `XML::Attribute` and not the parsers themselves the SAX parser currently doesn't decode entities. I'll sort this out so that users don't have to do this manually.
