### ISSUE TITLE
Handle lexing of certain HTML5 nesting rules

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#97]
HTML5 allows one to omit closing tags of certain elements which should be parsed as if the tags were present. For example:

```html
<ul>
    <li>Foo
    <li>Bar
</ul>
```

This should be parsed as:

```html
<ul>
    <li>Foo</li>
    <li>Bar</li>
</ul>
```

However, as per 13e2c3d82ffb9f32b863cb47f6808cf061e07095 it's parsed as following:

```html
<ul>
    <li>Foo
        <li>Bar</li>
    </li>
</ul>
```

There's bound to be a document somewhere written by the W3C that describes what behaviour to apply and where, otherwise I'll just have to implement it based on what I assume would be correct.

**Comment by YorickPeterse** [comment]
This seems to be covered by http://www.w3.org/TR/html5/syntax.html#syntax-tag-omission.

**Comment by abotalov** [comment]
I'd like to note that HTML 5.1 spec is has a bit more examples - http://www.w3.org/TR/html51/syntax.html#syntax-tag-omission

**Comment by YorickPeterse** [comment]
Tags to take care of:

* [x] html
* [x] head
* [x] body
* [ ] li
* [ ] dt 
* [ ] dd
* [ ] p
* [ ] rb
* [ ] rt
* [ ] rtc
* [ ] rp
* [ ] optgroup
* [ ] option
* [ ] colgroup
* [ ] thead
* [ ] tbody
* [ ] tfoot
* [ ] tr
* [ ] td
* [ ] th
